/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class VaneCollection {
  add(docs: any): Promise<Json>
  flush(): Promise<void>
  search(query: any): Promise<Json>
  delete(ids: Array<string>): Promise<bigint>
  reindex(): Promise<VaneReindexHandle>
  setUserDict(dict: any): Promise<void>
  dictState(): Promise<string>
}

export declare class VaneDb {
  static open(path: string, opts: any): Promise<VaneDb>
  collection(name: string, schema: any, opts: any): Promise<VaneCollection>
  collections(): Array<string>
  close(): Promise<void>
  export(dest: string): Promise<void>
}

/** SPEC §4.1 ReindexHandle napi 包装（progress/wait）。 */
export declare class VaneReindexHandle {
  progress(): number
  wait(): void
}

/** 返回词典日历版本（YYYY.MM，如 "2026.08"）。 */
export declare function dictVersion(): string

/**
 * 返回预编译 dict.bin（zstd 压缩 DAT + HMM，SPEC §5.2）的 Buffer 副本。
 *
 * 词典在 `Db.open` 时已自动加载；此函数供 JS 侧诊断/缓存/分发用。
 * 禁 postinstall（SPEC §12.3）：包结构纯数据 + include_bytes，无网络下载。
 */
export declare function loadDict(): Buffer
