/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class VaneCollection {
  add(docs: any): Promise<Json>
  flush(): Promise<void>
  search(query: any): Promise<Json>
  delete(ids: Array<string>): Promise<bigint>
  reindex(): Promise<void>
}
export declare class VaneDb {
  static open(path: string, opts: any): Promise<VaneDb>
  collection(name: string, schema: any, opts: any): Promise<VaneCollection>
  collections(): Array<string>
  close(): Promise<void>
  export(dest: string): Promise<void>
}
